#!/bin/bash
# Código de atualização do riso/risos
# Aqui ficará o procedimento de atualização para a versão mais recente.

echo "#Testando contato com barra de progresso"
echo "70"
sleep 2
echo "100"
