#!/bin/bash

# --------------------------------------------------------------------------
# Arquivo de instalação do riso e do risos
# --------------------------------------------------------------------------

dep_cli="avahi-utils rtorrent screen ntfsprogs ssh git-core"
dep_ser="avahi-utils avahi-daemon bittorrent rtorrent screen ntfsprogs grub2 ssh coreutils mkisofs genisoimage findutils bash passwd sed squashfs-tools casper rsync mount eject libdebian-installer4 os-prober ubiquity user-setup discover1 discover laptop-detect syslinux xterm util-linux xresprobe cdrecord git-core"

menu() {
    apt-get install -y dialog zenity
            opcao=$(zenity --width=400 --height=400 --text="Instalação do RISO" --list --checklist --column " " --column "Opcoes" TRUE RISOS TRUE RISO)
	# De acordo com a opção escolhida, executa funcoes
	case $opcao in
		"RISOS") instala_risos;;
		"RISO") instala_riso;;
		"RISOS|RISO") instala_riso; instala_risos;;
	esac



}

instala_riso() {
    echo "Instalando Cliente (RISO)..."
    
    echo "Baixando dependências..."
    apt-get install -y $dep_cli
    
    echo "Criando árvore de diretórios..."
    mkdir -p /usr/riso
    mkdir -p /usr/riso/imagens
    
    echo "Criando arquivo de inicialização..."
    echo '#!/bin/bash' > /usr/bin/riso
    echo '/usr/riso/riso $@' >> /usr/bin/riso
    chmod +x /usr/bin/riso
    
    echo "Movendo script..."
    cp ./src/biblioteca.sh /usr/riso/biblioteca.sh
    cp ./src/riso /usr/riso/riso
    chmod +x /usr/riso/riso
    cp ./conf/riso.conf /usr/riso/riso.conf


    	if [ -e /usr/riso/risoservice ]
	then 
		echo "Arquivo que mostra qual o nome do serviço do riso já existe."
	else
		nome_servico=_RISOdecom._tcp
		echo "Criando arquivo com o nome do serviço do riso..."
		echo "nome_servico=${nome_servico}" > /usr/riso/risoservice
	fi
    
    echo "Sistema instalado com sucesso."
    echo "Tente digitar 'riso' para iniciar."
}

instala_risos() {
    echo "Instalando Servidor (RISOS)..."
    
    echo "Liberando login como root..."
    echo -n "root:" > /etc/shadow.tmp
    pass=`cat /etc/shadow | grep \`who | awk 'NR==1{print $1}'\` | cut -d':' -f2`
    echo -n "${pass}:" >> /etc/shadow.tmp
    cat /etc/shadow | grep root | cut -d':' -f3,4,5,6,7,8,9 >> /etc/shadow.tmp
    cat /etc/shadow | grep -v root >> /etc/shadow.tmp
    mv /etc/shadow.tmp /etc/shadow
    
    echo "Baixando dependências..."
    apt-get install -y $dep_ser
    
    echo "Criando árvore de diretórios..."
    mkdir -p /usr/riso
    mkdir -p /usr/riso/imagens
    
    echo "Criando arquivo de inicialização..."
    echo '#!/bin/bash' > /usr/bin/risos
    echo '/usr/riso/risos $@' >> /usr/bin/risos
    chmod +x /usr/bin/risos
    
    echo "Movendo script..."
    cp ./src/biblioteca.sh /usr/riso/biblioteca.sh
    cp ./src/risos /usr/riso/risos
    chmod +x /usr/riso/risos
    
    echo "Gerando chaves rsa..."
    ssh-keygen -t 'rsa' -f '/root/.ssh/id_rsa' -N ''
    su -c "cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys2"
    
    echo "Criando variáveis de configuração..."
    
    #Pega partições
    partrec=`df -T | awk 'NR==2{print $1}'`
    partwindows=`blkid | grep ntfs | head -n1 | awk -F: {'print $1'}`
    partwindows2=`blkid | grep ntfs | grep -v ${partwindows} | head -n1 | awk -F: {'printf $1'}`	
    partlinux=`os-prober | grep linux | cut -d':' -f1`
    partswap=`blkid | grep swap | grep -v ram | cut -d':' -f1`
    
    #Pega sistema de arquivo das partiçoes.
    sa_partrec=`df -T | awk 'NR==2{print $2}'`
    sa_partlinux=`blkid ${partlinux} | cut -d'"' -f4`
    sa_partwindows=`blkid ${partwindows} | cut -d'"' -f4`
    sa_partwindows2=`blkid ${partwindows2} | cut -d'"' -f4`
    
    #Prepara grub2
    sed s/'GRUB_DEFAULT=0'/'GRUB_DEFAULT=1'/g -i /etc/default/grub
    sed s/'GRUB_DISTRIBUTOR=*'/'#GRUB_DISTRIBUTOR='/g -i /etc/default/grub
    echo 'GRUB_DISTRIBUTOR=Recuperacao' >> /etc/default/grub
    sed s/'#GRUB_DISABLE_LINUX_UUID=true'/'GRUB_DISABLE_LINUX_UUID=true'/g -i /etc/default/grub
    sed s/'#GRUB_DISABLE_LINUX_RECOVERY="true"'/'GRUB_DISABLE_LINUX_RECOVERY="true"'/g -i /etc/default/grub
    rm -f /etc/grub.d/20_memtest86+
    mv /etc/grub.d/10_linux /etc/grub.d/50_linux
    update-grub
     
	#Cria arquivo de configuração com as variáveis se ainda não existir
	if [ -e /usr/riso/riso.vars ]
	then 
		echo "Arquivo de configuração já existe e não será recriado."
	else
		echo "Criando arquivo de configuração..."
		echo "#Arquivo que contém as váriaveis que o riso usa (Automaticamente baixado do servidor risos) " > /usr/riso/riso.vars
		echo "" >> /usr/riso/riso.vars
		echo "# Variáveis com sistema de arquivo das partições" >> /usr/riso/riso.vars
		echo "sa_partrec=${sa_partrec}" >> /usr/riso/riso.vars
		echo "sa_partlinux=${sa_partlinux}" >> /usr/riso/riso.vars
		echo "sa_partwindows=${sa_partwindows}" >> /usr/riso/riso.vars
		echo "sa_partwindows2=${sa_partwindows2}" >> /usr/riso/riso.vars
		echo "" >> /usr/riso/riso.vars
		echo "# Variáveis com tamanho das imagens geradas no servidor" >> /usr/riso/riso.vars
		echo "tamlinux=123456789" >> /usr/riso/riso.vars
		echo "tamwindows=123456789" >> /usr/riso/riso.vars
		echo "tamwindows2=123456789" >> /usr/riso/riso.vars
		echo "" >> /usr/riso/riso.vars
		echo "# Localização dos sistemas operacionais no HD" >> /usr/riso/riso.vars
		echo "partswap=${partswap}" >> /usr/riso/riso.vars
		echo "partrec=${partrec}" >> /usr/riso/riso.vars
		echo "partlinux=${partlinux}" >> /usr/riso/riso.vars
		echo "partwindows=${partwindows}" >> /usr/riso/riso.vars
		echo "partwindows2=${partwindows2}" >> /usr/riso/riso.vars
	fi


	if [ -e /usr/riso/risoservice ]
	then 
		echo "Arquivo que mostra qual o nome do serviço do riso já existe."
		echo "Caso seja necessário trocar, edite manualmente o arquivo /usr/riso/risoservice."
	else
		nome_servico=_RISOdecom._tcp
		echo "Criando arquivo com o nome do serviço do riso..."
		echo "nome_servico=${nome_servico}" > /usr/riso/risoservice
	fi
	 
	
    
       
    # preinst script for remastersys
    if [ -d /remastersys ]; then
    mv /remastersys /home
    fi

    if [ -f /etc/remastersys.conf ]; then
    mv /etc/remastersys.conf /etc/remastersys.conf.old
    fi

    if [ -f /etc/remastersys/isolinux/splash.pcx ]; then
    mv /etc/remastersys/isolinux/splash.pcx /etc/remastersys/isolinux/splash.pcx.saved
    fi

    if [ -f /etc/remastersys/isolinux/splash.rle ]; then
    mv /etc/remastersys/isolinux/splash.rle /etc/remastersys/isolinux/splash.rle.saved
    fi

    if [ -f /etc/remastersys/grub/splash.xpm.gz ]; then
    mv /etc/remastersys/grub/splash.xpm.gz /etc/remastersys/grub/splash.xpm.gz.saved
    fi

    #Instalação do remastersys
    mkdir -p /etc/remastersys
    cp -r ./src/remastersys/remastersys/grub /etc/remastersys
    cp -r ./src/remastersys/remastersys/isolinux /etc/remastersys
    cp -r ./src/remastersys/remastersys/preseed /etc/remastersys
    cp ./src/remastersys/remastersys.conf /etc/remastersys.conf

    # postinst script for remastersys
    if [ -f /etc/remastersys/isolinux/splash.pcx.saved ]; then
    mv /etc/remastersys/isolinux/splash.pcx.saved /etc/remastersys/isolinux/splash.pcx
    fi

    if [ -f /etc/remastersys/isolinux/splash.rle.saved ]; then
    mv /etc/remastersys/isolinux/splash.rle.saved /etc/remastersys/isolinux/splash.rle
    fi

    if [ -f /etc/remastersys/grub/splash.xpm.gz.saved ]; then
    mv /etc/remastersys/grub/splash.xpm.gz.saved /etc/remastersys/isolinux/splash.xpm.gz
    fi

    if [ -f /etc/remastersys.conf.old ]; then
    mv /etc/remastersys.conf.old /etc/remastersys.conf
    fi
    
    #Se estiver usando windows 7. Muda arquivo de boot para não usar mais UUID.
    windows7=`os-prober | grep "Windows 7"`
    if [ ! -z "$windows7" ]; then
        echo "Configurando Windows 7..."
	    umount /mnt 2> /dev/null
	    mount ${partwindows} /mnt
	    cp ./conf/BCD /mnt/Boot/BCD
	    umount /mnt 2> /dev/null
    fi

    echo "Sistema instalado com sucesso"
    echo "Tente risos para iniciar"
}



#Verifica se usuário é o root antes de executar.
USER=`id -u`
if [ $USER == '0' ]; then
    menu
else
    echo "Só o root pode fazer isso, jovenzinho!"
fi
